baseurl = "/"
languageCode = "en-us"
title = "Probabilidade e Estat√≠stica"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "../probabilidade-estatistica.github.io"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Sobre"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/lizerb"
[[menu.main]]
    name = "Livro"
    url = "https://bookdown.org/ndphillips/YaRrr/"
[[menu.main]]
    name = "Equipe"
    url = "/equipe/"
[[menu.main]]
    name = "Slides"
    url = "/slides/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "prob_header.ico"

    [params.logo]
    url = "prob_header.png"
    width = 50
    height = 50
    alt = "Logo"

